# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dac72c02dfc65a6ab46196c952ab9d8b4df3d2511ed9cc38d7bea68089274f025377e6b5dd21093812d14dd54f6235437dfbbf076835a8af43f98de61dadcb4

test:
  secret_key_base: 47c16eab6de3867f22563f439db28100b464690f2b9381e78f401fd361e20f74b30cdc328f14c43de1912416e4734b14d053e463ec872f63b20aa3837ade9b7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
